def factorial(n):
    return n * factorial(n - 1)


print(factorial(4))

'''La funci贸n no tiene una condici贸n de terminaci贸n, por lo tanto Python arrojara una excepci贸n (RecursionError: maximum recursion depth exceeded)'''